# Generated by Django 5.1 on 2025-11-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chomp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='html_content',
            new_name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
