# Generated by Django 5.1 on 2025-11-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chomp', '0002_rename_html_content_article_content_article_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
