# Generated by Django 5.1 on 2025-11-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chomp', '0004_alter_article_options_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
