# Generated by Django 5.1 on 2025-11-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chomp', '0006_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='apnews', max_length=50),
        ),
    ]
