# Generated by Django 5.1 on 2025-11-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chomp', '0007_article_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
